package com.example.shoppingmallsystem.util;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

public class MySQLhelper extends SQLiteOpenHelper {

    public static final String DB_NAME = "ShoppingMallInfo";
    public static final int VERSION = 1;

    public MySQLhelper(@Nullable Context context, @Nullable String DB_NAME, @Nullable SQLiteDatabase.CursorFactory factory, int VERSION) {
        super(context, DB_NAME, factory, VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL("CREATE TABLE userInfo(_id INTEGER PRIMARY KEY AUTOINCREMENT ,userName VERVHAR(20),password VERVHAR(20),nickName VERVHAR(20),phoneNumb VERVHAR(20),schoolName VERVHAR(20),apartmentNumb VERVHAR(20) , money REAL)");
        db.execSQL("CREATE TABLE storeInfo(_id INTEGER PRIMARY KEY autoincrement ,ID VERVHAR(20),picNumb VERVHAR(20),storeName VERVHAR(20),storeScore VERVHAR(20),storeSell VERVHAR(20) ,storeSign VERVHAR(20) ,storeIntro text )");
        db.execSQL("CREATE TABLE goodsInfo(_id INTEGER PRIMARY KEY autoincrement ,ID VERVHAR(20),goodsJson text)");
        db.execSQL("CREATE TABLE messagesInfo(_id INTEGER PRIMARY KEY autoincrement ,ID INTEGER,img_id VERVHAR(20),message text,userName VERVHAR(20),time VERVHAR(20))");
        db.execSQL("CREATE TABLE orderInfo(_id INTEGER PRIMARY KEY autoincrement ,userName VERVHAR(20),time VERVHAR(20),goodsJson text)");


        db.execSQL("INSERT INTO userInfo(userName,password,nickName,phoneNumb,schoolName,apartmentNumb,money) VALUES ('aaa','111','Акмарал','15632586254','КГТУ','Корпус№2',0)");
        db.execSQL("INSERT INTO messagesInfo(ID,img_id,message,userName,time) VALUES (1,'1','Я думаю, что товары в магазине 1 очень плохие.','aaa','2021.12.15 12:08')");


        db.execSQL("INSERT INTO storeInfo (ID, picNumb, storeName, storeScore, storeSell, storeSign, storeIntro) values ('2', '4', ' Магазин Lining', '4.7', '253', 'Добро пожаловать в Lining!', 'Компания Lining была основана в 1990 году и является одним из ведущих брендов спортивной одежды и обуви в Китае. Lining известен своими высококачественными продуктами, предназначенными для спортсменов и любителей активного отдыха. Мы предлагаем широкий ассортимент товаров для различных видов спорта и фитнеса. Мы стремимся к инновациям и улучшению качества жизни наших клиентов. Мы также активно развиваемся на международном рынке, предлагая товары в более чем 60 странах мира. Слоган Lining: \"Побеждай, как Lining!\"')");
        db.execSQL("INSERT INTO storeInfo (ID, picNumb, storeName, storeScore, storeSell, storeSign, storeIntro) values ('3', '1', 'Магазин Gucci', '4.9', '1200', 'Gucci — символ роскоши и стиля', 'Gucci — это один из самых известных мировых брендов, основанный в 1921 году в Италии. Компания производит высококачественные товары, включая одежду, обувь, аксессуары, парфюмерию и сумки. Gucci известен своими смелыми и инновационными дизайнами, которые гармонично сочетают в себе традиции итальянского мастерства и современные тренды. Бренд стал символом роскоши и утонченного стиля, а его продукция востребована на рынках по всему миру. Gucci часто используется знаменитыми личностями и влиятельными людьми, символизируя статус и изысканный вкус. Мы приглашаем вас в мир эксклюзивных коллекций и безупречного качества от Gucci.')");
        db.execSQL("INSERT INTO storeInfo (ID, picNumb, storeName, storeScore, storeSell, storeSign, storeIntro) values ('4', '6', 'Магазин Louis Vuitton', '4.9', '1500', 'Louis Vuitton — символ утонченности', 'Louis Vuitton — это один из самых известных и престижных мировых брендов, основанный в 1854 году во Франции. Компания производит широкий ассортимент товаров, включая сумки, одежду, обувь, аксессуары и парфюмерию. Продукция Louis Vuitton известна своим высоким качеством, элегантным дизайном и мастерством исполнения. Бренд Louis Vuitton ассоциируется с роскошью, эксклюзивностью и статусом, являясь символом утонченного вкуса и высокого класса. Louis Vuitton использует инновационные технологии и с любовью сохраняет традиции ремесленного мастерства, создавая произведения, которые ценятся по всему миру.')");
        db.execSQL("INSERT INTO storeInfo (ID, picNumb, storeName, storeScore, storeSell, storeSign, storeIntro) values ('5', '2', 'Магазин Prada', '4.7', '800', 'Prada — символ стиля', 'Prada — один из ведущих итальянских брендов в мире моды, основанный в 1913 году Марио Прада. Компания известна своим уникальным и элегантным дизайном, который сочетает в себе инновации и традиции. Prada предлагает широкий ассортимент одежды, обуви, сумок и аксессуаров. Бренд отличается изысканностью и высоким качеством материалов, а также мастерством в производстве. Стиль Prada востребован среди знаменитостей и модных экспертов по всему миру. Это бренд, который олицетворяет итальянский стиль, роскошь и эксклюзивность.')");
        db.execSQL("INSERT INTO storeInfo (ID, picNumb, storeName, storeScore, storeSell, storeSign, storeIntro) values ('7', '0', 'Магазин Chanel', '4.9', '105', 'Chanel — символ элегантности', 'Chanel — один из самых известных и влиятельных брендов в мире моды, основанный в 1909 году Габриэль Коко Шанель. Бренд известен своими культовыми изделиями, такими как маленькая черная платье, парфюмы Chanel No. 5 и аксессуары, а также своей приверженностью к элегантности и женственности. Chanel занимает особое место в мире моды благодаря своему уникальному подходу к дизайну и инновациям, а также неизменно высокому качеству своих товаров. Визитной карточкой бренда стали элегантные костюмы, а также стиль, сочетающий в себе классику и современные тренды.')");
        db.execSQL("INSERT INTO storeInfo (ID, picNumb, storeName, storeScore, storeSell, storeSign, storeIntro) values ('8', '7', 'Магазин Versace', '4.8', '312', 'Versace — воплощение роскоши', 'Versace — один из самых известных итальянских брендов, основанный в 1978 году Джанни Версаче. Бренд известен своей роскошной и яркой продукцией, включающей одежду, аксессуары, обувь и парфюмерию. Versace стал синонимом элегантности и гламура, активно использующий яркие цвета, сложные узоры и инновационные формы в своих коллекциях. После трагической гибели Джанни в 1997 году, его сестра Донателла Версаче продолжила развивать бренд, сохраняя его уникальную идентичность и расширяя международное присутствие.')");
        db.execSQL("INSERT INTO storeInfo (ID, picNumb, storeName, storeScore, storeSell, storeSign, storeIntro) values ('9', '5', 'Магазин Balenciaga', '4.7', '274', 'Balenciaga — революция в мире моды', 'Balenciaga — испанский модный дом, основанный Кристобалем Баленсиагой в 1917 году. Бренд стал известен благодаря своему авангардному подходу к дизайну, инновационным конструкциям и архитектурным силуэтам. С момента прихода Демны Гвасалии в качестве креативного директора в 2015 году, Balenciaga вновь стал лидером в индустрии, привлекая внимание молодежной аудитории и задавая тренды в мире уличной моды и высокой моды. В коллекциях Balenciaga часто используются элементы, которые бросают вызов традиционным представлениям о стиле и роскоши.')");
        db.execSQL("INSERT INTO storeInfo (ID, picNumb, storeName, storeScore, storeSell, storeSign, storeIntro) values ('10', '3', 'Магазин Dolce & Gabbana', '4.8', '523', 'Dolce & Gabbana — итальянская роскошь', 'Dolce & Gabbana — один из самых известных итальянских модных домов, основанный Доменико Дольче и Стефано Габбаной в 1985 году. Бренд славится своими роскошными и яркими коллекциями, сочетающими традиционные итальянские мотивы с современными инновациями. Dolce & Gabbana известен своими элегантными вечерними нарядами, женственными силуэтами, а также смелыми мужскими коллекциями. С момента своего основания бренд закрепил за собой статус символа утонченной роскоши и высокого стиля, вдохновляя модный мир и создавая тренды.')");


        db.execSQL("INSERT INTO goodsInfo (ID, goodsJson) VALUES (1, '{\"itemsLeft\":[{\"title\":\"Сумки\"},{\"title\":\"Обувь\"},{\"title\":\"Одежда\"},{\"title\":\"Аксессуары\"}],\"itemsRight\":[{\"content\":\"Это описание товара...\",\"name\":\"Сумка 1\",\"number\":0,\"picNumb\":\"10\",\"price\":\"1599.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 2\",\"number\":0,\"picNumb\":\"11\",\"price\":\"3499.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 3\",\"number\":0,\"picNumb\":\"12\",\"price\":\"2299.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 4\",\"number\":0,\"picNumb\":\"13\",\"price\":\"1799.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"1299.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 2\",\"number\":0,\"picNumb\":\"4\",\"price\":\"2499.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 3\",\"number\":0,\"picNumb\":\"9\",\"price\":\"1999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 1\",\"number\":0,\"picNumb\":\"6\",\"price\":\"2599.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 2\",\"number\":0,\"picNumb\":\"5\",\"price\":\"3199.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 3\",\"number\":0,\"picNumb\":\"1\",\"price\":\"3899.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 1\",\"number\":0,\"picNumb\":\"2\",\"price\":\"799.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 2\",\"number\":0,\"picNumb\":\"5\",\"price\":\"599.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 3\",\"number\":0,\"picNumb\":\"7\",\"price\":\"1299.99\",\"title\":\"Аксессуары\"}]}')");
        db.execSQL("INSERT INTO goodsInfo (ID, goodsJson) VALUES (2, '{\"itemsLeft\":[{\"title\":\"Сумки\"},{\"title\":\"Обувь\"},{\"title\":\"Одежда\"},{\"title\":\"Аксессуары\"}],\"itemsRight\":[{\"content\":\"Это описание товара...\",\"name\":\"Спортивная сумка\",\"number\":0,\"picNumb\":\"1\",\"price\":\"2599.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка на пояс\",\"number\":0,\"picNumb\":\"9\",\"price\":\"5999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Барсетка\",\"number\":0,\"picNumb\":\"2\",\"price\":\"7999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Рюкзак\",\"number\":0,\"picNumb\":\"3\",\"price\":\"12999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 1\",\"number\":0,\"picNumb\":\"4\",\"price\":\"3999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 2\",\"number\":0,\"picNumb\":\"5\",\"price\":\"6999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 3\",\"number\":0,\"picNumb\":\"6\",\"price\":\"4999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\" Спортивный костюм\",\"number\":0,\"picNumb\":\"7\",\"price\":\"8999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Двойка Lining\",\"number\":0,\"picNumb\":\"8\",\"price\":\"14999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Спортивка\",\"number\":0,\"picNumb\":\"0\",\"price\":\"19999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Кепка\",\"number\":0,\"picNumb\":\"11\",\"price\":\"2999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Повязка головы\",\"number\":0,\"picNumb\":\"12\",\"price\":\"4499.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Для рук\",\"number\":0,\"picNumb\":\"13\",\"price\":\"6999.99\",\"title\":\"Аксессуары\"}]}')");
        db.execSQL("INSERT INTO goodsInfo (ID, goodsJson) VALUES (3, '{\"itemsLeft\":[{\"title\":\"Сумки\"},{\"title\":\"Кофты\"},{\"title\":\"Духи\"}],\"itemsRight\":[{\"content\":\"Это описание товара...\",\"name\":\"Сумка 1\",\"number\":0,\"picNumb\":\"6\",\"price\":\"16999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"35999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"45999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Кофта 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"24999.99\",\"title\":\"Кофты\"},{\"content\":\"Это описание товара...\",\"name\":\"Кофта 2\",\"number\":0,\"picNumb\":\"5\",\"price\":\"32999.99\",\"title\":\"Кофты\"},{\"content\":\"Это описание товара...\",\"name\":\"Кофта 3\",\"number\":0,\"picNumb\":\"7\",\"price\":\"38999.99\",\"title\":\"Кофты\"},{\"content\":\"Это описание товара...\",\"name\":\"Духи 1\",\"number\":0,\"picNumb\":\"1\",\"price\":\"64999.99\",\"title\":\"Духи\"},{\"content\":\"Это описание товара...\",\"name\":\"Духи 2\",\"number\":0,\"picNumb\":\"4\",\"price\":\"79999.99\",\"title\":\"Духи\"},{\"content\":\"Это описание товара...\",\"name\":\"Духи 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"99999.99\",\"title\":\"Духи\"}]}')");
        db.execSQL("INSERT INTO goodsInfo (ID, goodsJson) VALUES (4, '{\"itemsLeft\":[{\"title\":\"Сумки\"},{\"title\":\"Бомбер\"}],\"itemsRight\":[{\"content\":\"Это описание товара...\",\"name\":\"Сумка 1\",\"number\":0,\"picNumb\":\"6\",\"price\":\"16999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"35999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"45999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Бомбер 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"24999.99\",\"title\":\"Бомбер\"},{\"content\":\"Это описание товара...\",\"name\":\"Бомбер 2\",\"number\":0,\"picNumb\":\"5\",\"price\":\"32999.99\",\"title\":\"Бомбер\"},{\"content\":\"Это описание товара...\",\"name\":\"Бомбер 3\",\"number\":0,\"picNumb\":\"7\",\"price\":\"38999.99\",\"title\":\"Бомбер\"}]}')");
        db.execSQL("INSERT INTO goodsInfo (ID, goodsJson) VALUES (5, '{\"itemsLeft\":[{\"title\":\"Сумки\"},{\"title\":\"Одежда\"}],\"itemsRight\":[{\"content\":\"Это описание товара...\",\"name\":\"Сумка 1\",\"number\":0,\"picNumb\":\"6\",\"price\":\"16999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"35999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"45999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 1\",\"number\":0,\"picNumb\":\"1\",\"price\":\"64999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 2\",\"number\":0,\"picNumb\":\"4\",\"price\":\"79999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"99999.99\",\"title\":\"Одежда\"}]}')");
        db.execSQL("INSERT INTO goodsInfo (ID, goodsJson) VALUES (6, '{\"itemsLeft\":[{\"title\":\"Сумки\"},{\"title\":\"Обувь\"},{\"title\":\"Одежда\"},{\"title\":\"Аксессуары\"}],\"itemsRight\":[{\"content\":\"Это описание товара...\",\"name\":\"Сумка 1\",\"number\":0,\"picNumb\":\"6\",\"price\":\"16999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"35999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"45999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"24999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 2\",\"number\":0,\"picNumb\":\"5\",\"price\":\"32999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 3\",\"number\":0,\"picNumb\":\"7\",\"price\":\"38999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 1\",\"number\":0,\"picNumb\":\"1\",\"price\":\"64999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 2\",\"number\":0,\"picNumb\":\"4\",\"price\":\"79999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"99999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"19999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"27999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 3\",\"number\":0,\"picNumb\":\"5\",\"price\":\"35999.99\",\"title\":\"Аксессуары\"}]}')");
        db.execSQL("INSERT INTO goodsInfo (ID, goodsJson) VALUES (7, '{\"itemsLeft\":[{\"title\":\"Сумки\"},{\"title\":\"Обувь\"},{\"title\":\"Одежда\"},{\"title\":\"Аксессуары\"}],\"itemsRight\":[{\"content\":\"Это описание товара...\",\"name\":\"Сумка 1\",\"number\":0,\"picNumb\":\"6\",\"price\":\"16999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"35999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"45999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"24999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 2\",\"number\":0,\"picNumb\":\"5\",\"price\":\"32999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 3\",\"number\":0,\"picNumb\":\"7\",\"price\":\"38999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 1\",\"number\":0,\"picNumb\":\"1\",\"price\":\"64999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 2\",\"number\":0,\"picNumb\":\"4\",\"price\":\"79999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"99999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"19999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"27999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 3\",\"number\":0,\"picNumb\":\"5\",\"price\":\"35999.99\",\"title\":\"Аксессуары\"}]}')");
        db.execSQL("INSERT INTO goodsInfo (ID, goodsJson) VALUES (8, '{\"itemsLeft\":[{\"title\":\"Сумки\"},{\"title\":\"Обувь\"},{\"title\":\"Одежда\"},{\"title\":\"Аксессуары\"}],\"itemsRight\":[{\"content\":\"Это описание товара...\",\"name\":\"Сумка 1\",\"number\":0,\"picNumb\":\"6\",\"price\":\"16999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"35999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"45999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"24999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 2\",\"number\":0,\"picNumb\":\"5\",\"price\":\"32999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 3\",\"number\":0,\"picNumb\":\"7\",\"price\":\"38999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 1\",\"number\":0,\"picNumb\":\"1\",\"price\":\"64999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 2\",\"number\":0,\"picNumb\":\"4\",\"price\":\"79999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"99999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"19999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"27999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 3\",\"number\":0,\"picNumb\":\"5\",\"price\":\"35999.99\",\"title\":\"Аксессуары\"}]}')");
        db.execSQL("INSERT INTO goodsInfo (ID, goodsJson) VALUES (9, '{\"itemsLeft\":[{\"title\":\"Сумки\"},{\"title\":\"Обувь\"},{\"title\":\"Одежда\"},{\"title\":\"Аксессуары\"}],\"itemsRight\":[{\"content\":\"Это описание товара...\",\"name\":\"Сумка 1\",\"number\":0,\"picNumb\":\"2\",\"price\":\"16999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"35999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"45999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"24999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 2\",\"number\":0,\"picNumb\":\"5\",\"price\":\"32999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 3\",\"number\":0,\"picNumb\":\"7\",\"price\":\"38999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 1\",\"number\":0,\"picNumb\":\"1\",\"price\":\"64999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 2\",\"number\":0,\"picNumb\":\"4\",\"price\":\"79999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"99999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"19999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"27999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 3\",\"number\":0,\"picNumb\":\"5\",\"price\":\"35999.99\",\"title\":\"Аксессуары\"}]}')");
        db.execSQL("INSERT INTO goodsInfo (ID, goodsJson) VALUES (10, '{\"itemsLeft\":[{\"title\":\"Сумки\"},{\"title\":\"Обувь\"},{\"title\":\"Одежда\"},{\"title\":\"Аксессуары\"}],\"itemsRight\":[{\"content\":\"Это описание товара...\",\"name\":\"Сумка 1\",\"number\":0,\"picNumb\":\"6\",\"price\":\"16999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"35999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Сумка 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"45999.99\",\"title\":\"Сумки\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"24999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 2\",\"number\":0,\"picNumb\":\"5\",\"price\":\"32999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Обувь 3\",\"number\":0,\"picNumb\":\"7\",\"price\":\"38999.99\",\"title\":\"Обувь\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 1\",\"number\":0,\"picNumb\":\"1\",\"price\":\"64999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 2\",\"number\":0,\"picNumb\":\"4\",\"price\":\"79999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Одежда 3\",\"number\":0,\"picNumb\":\"8\",\"price\":\"99999.99\",\"title\":\"Одежда\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 1\",\"number\":0,\"picNumb\":\"3\",\"price\":\"19999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 2\",\"number\":0,\"picNumb\":\"2\",\"price\":\"27999.99\",\"title\":\"Аксессуары\"},{\"content\":\"Это описание товара...\",\"name\":\"Аксессуар 3\",\"number\":0,\"picNumb\":\"5\",\"price\":\"35999.99\",\"title\":\"Аксессуары\"}]}')");

        db.execSQL("INSERT INTO orderInfo (userName, time, goodsJson) VALUES ('JohnDoe', '2024-12-20 12:00:00', '{\"item1\": \"Gucci Bag\", \"item2\": \"Gucci Shoes\"}')");
        db.execSQL("INSERT INTO orderInfo (userName, time, goodsJson) VALUES ('AliceSmith', '2024-12-20 14:30:00', '{\"item1\": \"Gucci Wallet\", \"item2\": \"Gucci Sunglasses\"}')");
        db.execSQL("INSERT INTO orderInfo (userName, time, goodsJson) VALUES ('BobJohnson', '2024-12-20 16:00:00', '{\"item1\": \"Gucci Belt\", \"item2\": \"Gucci Hat\"}')");


    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {

    }
}
